name: CD Workflow

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "gitappAA"

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Hello World"

    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.Azure_Key }}
          package: './publish'
