name: CI/CD Workflow

on:
  workflow_dispatch

env:
  AZURE_WEBAPP_NAME: "gitappAA"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore ./githubWorkFlows/githubWorkFlows.csproj

      - name: Build project
        run: dotnet build ./githubWorkFlows/githubWorkFlows.csproj --configuration Release

      - name: Publish project
        run: dotnet publish ./githubWorkFlows/githubWorkFlows.csproj --configuration Release --output ./publish

      - name: Deploy to webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.Azure_Key }}
          images: './publish' # Path to the deployment package
